## ML Model Training and Experiments

- Converting data for ML model Consumable
- Adding Weight & Biases for Experiment Tracking 
- Training Different Model 
- Evaluations

#### Data Conversion

In [3]:
# imports
import pandas as pd

In [4]:
df = pd.read_csv("../dataset/ml_raw_data.csv")
df.head()

   age     sex  ...  diet_quality_score  has_heart_disease
0   44    Male  ...                62.9                  0
1   57    Male  ...                74.6                  1
2   29    Male  ...                65.7                  0
3   72    Male  ...                48.5                  1
4   62  Female  ...                47.3                  1

[5 rows x 24 columns]

In [5]:
df.columns.groupby(df.dtypes)

{int64: ['age', 'resting_bp_systolic', 'resting_bp_diastolic', 'hdl', 'ldl', 'triglycerides', 'resting_heart_rate', 'max_heart_rate_achieved', 'exercise_minutes_per_week', 'daily_steps', 'has_heart_disease'], str: ['sex', 'chest_pain_type', 'smoker_status'], float64: ['hba1c', 'bmi', 'st_depression', 'alcohol_units_per_week', 'sleep_hours', 'stress_score', 'diet_quality_score'], bool: ['exercise_induced_angina', 'family_history', 'wearable_owner']}

In [6]:
NUMERICAL_FEATURE = ['age', 'resting_bp_systolic', 'resting_bp_diastolic', 'hdl', 'ldl', 'triglycerides', 'resting_heart_rate', 'max_heart_rate_achieved', 'exercise_minutes_per_week', 'daily_steps','hba1c', 'bmi', 'st_depression', 'alcohol_units_per_week', 'sleep_hours', 'stress_score', 'diet_quality_score'] 
CATEGORICAL_FEATURE = ['sex', 'chest_pain_type', 'smoker_status', 'exercise_induced_angina', 'family_history', 'wearable_owner'] 
TARGET_FEATURE = 'has_heart_disease'

In [7]:
# Normalizing the numerical feature 
df[NUMERICAL_FEATURE].head()

   age  resting_bp_systolic  ...  stress_score  diet_quality_score
0   44                  117  ...          19.8                62.9
1   57                  139  ...          45.8                74.6
2   29                  128  ...          17.7                65.7
3   72                  132  ...          63.6                48.5
4   62                  116  ...          58.7                47.3

[5 rows x 17 columns]

In [9]:
X = df[NUMERICAL_FEATURE + CATEGORICAL_FEATURE]
y = df[TARGET_FEATURE]

In [10]:
y.head()

0    0
1    1
2    0
3    1
4    1
Name: has_heart_disease, dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
        [
            ('num-scaler',StandardScaler(), df[NUMERICAL_FEATURE]),
            ('cat-encoder',OneHotEncoder(),df[CATEGORICAL_FEATURE])
        ]
)

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train, y_test = train_test_split(X,y,train_size=0.8)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((7200, 23), (1800, 23), (7200,), (1800,))

In [ ]:
# Train Different Models with W&B Tracing

import wandb
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

run_rf = wandb.init(
    project="mtech-demo-experiments",
    name="random-forest-run",
    config={
        "algorithm": "RandomForest",
        "n_estimators": 100,
        "max_depth": 10,
        "random_state": 42,
    }
)

rforest_classifier = Pipeline(
    steps=[
        ('data-preprocessor',preprocessor),
        ('rforest-classifier',RandomForestClassifier(n_estimators=100,max_depth=10,random_state=42))
    ]
)

rforestM = rforest_classifier.fit(X_train,y_train)

# evalution and scores